version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CI=false
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend:
    build:
       context: ./backend
    ports:
      - "3001:3001"
    volumes:
       - ./backend:/app
       - /app/node_modules
    environment:
      - NODE_ENV=development
       - SUPABASE_URL=https://aolinrjyoaxafvmedasr.supabase.co
       - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvbGlucmp5b2F4YWZ2bWVkYXNyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MzczNDM4NywiZXhwIjoyMDY5MzEwMzg3fQ.AknkGIvaWccrdOl_UW_LIMLuWzRpEZ351qp8o2xxWlc
      - PORT=3001

    